config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blogs
  
  root 'blogs#index'          
  get '/new' => 'blogs#new'       # 投稿画面 
  post '/complete' => 'blogs#create'    # 投稿機能 
  post '/login' => 'blogs#login'      # ユーザー登録
  delete '/:id' => 'blogs#destroy'
  get '/:id/edit' => 'blogs#edit'
  patch '/id' => 'blogs#update'

  post '/like/:blog_id' => 'likes#like', as: 'like'
  delete '/like/:blog_id' => 'likes#unlike', as: 'unlike'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blog

         has_many :likes, dependent: :destroy
         has_many :like_blogs, through: :likes, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @blogs = Blog.all.order("id DESC").page(params[:page]).per(5)
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(blog_params)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  helper_method :current_user, :logged_in?

  private
  def blog_params
    params.permit(:title, :image, :content).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(blog_id: @blog.id)
    like.save
    
  end

  def unlike
    like = current_user.likes.find_by(blog_id: @blog.id)
    like.destroy
    
  end

  private
  
  def set_variables
    @blog = Blog.find(params[:blog_id])
    @id_name = "#like-link-#{@blog.id}"
    @id_heart = "#heart-#{@blog.id}"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/blogs/_blog.html.erb
<li>
    <h2><%= blog.title %></h2>
    <div class="time">
    <p><%= blog.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    </div>
    <div class="user_name">
        <a>
          <span>投稿者</span><%= blog.user.nickname %>さん
        </a>
    </div>
    <% if blog.image != "" %>
      <p><img src="<%= blog.image %>"></p>
    <% end %>
    <p><%= blog.content %></p>
    
    <% if user_signed_in? %>
      <%= render 'likes/like_links', blog: blog %>
    <% end %>
    
  </li>
  <% if user_signed_in? && blog.user_id == current_user.id %>
    <ul class="button">
      <li><%= link_to '編集', "/#{blog.id}/edit", method: :get%></li>
      <li><%= link_to '削除', "/#{blog.id}", method: :delete, data: {confirm: "本当に削除しますか？"} %></li>
    </ul>
    <% end %>

app/views/blogs/create.html.erb
<div class="contents_row">
  <div class="success">
    <h3>
    投稿が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧に戻る</a>
  </div>
</div>

app/views/blogs/destroy.html.erb
<p>削除しました。</p>
<%= link_to '一覧へ戻る', "/" %>

app/views/blogs/edit.html.erb
<div class="contents_row">
  <a href="/">一覧へ戻る</a>
  <%= form_for @blog do |f| %>
    <h3>
      編集する
    </h3>
    <div class="form-group">
     <p><input type="text" name="title" placeholder="タイトル"></p>
    </div>
    <div class="form-group">
    <p><input type="text" name="image" placeholder="Image Url"></p>
    </div>
    <div class="form-group">
    <textarea name="content" placeholder="記事を書いてください" rows="10" cols="50"></textarea>
    </div>
    <p><input id="edit_btn" type="submit" value="編集"></p>
    <small id="submit-tip" class="form-text text-muted">
    投稿する前に編集内容を見直してください!
    </small>
  <% end %>
</div>

app/views/blogs/index.html.erb
<ul class="list_blog">
  <% @blogs.each do |blog| %>
  <%= render partial: "blog", locals: { blog: blog } %>
  <% end %>
  <%= paginate(@blogs) %>
</ul>

app/views/blogs/new.html.erb
<div class="contents_row">
  <a href="/blogs">一覧にもどる</a>
</div>
<div class="content">
<%= form_for @blog do |f| %>
    <div class="form-group">
        <p><input type="text" name="title" placeholder="タイトル"></p>
    </div>

    <div class="form-group">
        <p><input type="text" name="image" placeholder="Image Url"></p>
    </div>

    <div class="form-group"> 
        <textarea name="content" placeholder="記事を書いてください" rows="10" cols="50"></textarea>
    </div>
    <p><input id="btn" type="submit" value="投稿"></p>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
</div>
<% end %>

app/views/blogs/update.html.erb
<p>更新しました。</p>
<%= link_to '一覧へ戻る', "/"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1>MY BLOG</h1>
      </div>
      <% if user_signed_in? %>
      <p class="name">ユーザー：<%= current_user.nickname %>さん</p>
      <ul class="nav">
        <li><a href="/new" >新規投稿</a></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
    <% else %>
    <ul class="nav">
     <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
     <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
    </ul>
    <% end %>
    </header> 
    <%= yield %>

    <footer>
      <p>
        Copyright Myblog 2019.
      </p>
    </footer>

  </body>
</html>

app/views/likes/_like_links.html.erb
 <div class="like-link" id="like-link-<%= blog.id %>">
  <% if current_user.likes.find_by(blog_id: blog.id) %>
    <%= link_to unlike_path(blog.id), method: :delete, remote: true do %>
      <div class = "like__button">❤️
        <%= blog.likes.count.to_s %>
      </div>
    <% end %>
  <% else %>
    <%= link_to like_path(blog.id), method: :post, remote: true do %>
      <div class = "like__button">♡️
        <%= blog.likes.count.to_s %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= j(render("likes/like_links", blog: @blog  )) %>');
$("<%= @id_heart %>").removeClass('♡️');
$("<%= @id_heart %>").addClass('❤️');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= j(render("likes/like_links", blog: @blog  )) %>');
$("<%= @id_heart %>").addClass('❤️');
$("<%= @id_heart %>").removeClass('♡️');